disabled_rules:
  - trailing_whitespace
included:
  - Sources
excluded:
  - Tests
line_length: 120
file_length:
  warning: 500
  error: 1200
large_tuple:
  warning: 3
  error: 4
type_body_length:
  warning: 300
  error: 500
type_name:
  min_length: 3
  max_length:
    warning: 40
    error: 50
identifier_name:
  min_length:
    error: 2
  max_length:
    warning: 45
    error: 60
reporter: "xcode"
